coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        informational: true

comment:
  layout: "condensed_header, diff, flags, components"
  require_changes: true
